services:
  flix-api:

    build: .

    container_name: flix_api_service

    restart: always

    ports:
      - "8000:8000"

    volumes:
      - .:/Flix-API

    command: python manage.py runserver 0.0.0.0:8000