# Generated by Django 5.2.4 on 2025-07-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nascionalidade', models.CharField(blank=True, choices=[('BR', 'Brasileiro'), ('US', 'Americano'), ('FR', 'Francês'), ('ES', 'Espanhol'), ('IT', 'Italiano'), ('JP', 'Japonês'), ('CN', 'Chinês'), ('IN', 'Indiano'), ('DE', 'Alemão'), ('RU', 'Russo'), ('UK', 'Britânico'), ('AU', 'Australiano')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Ator',
                'verbose_name_plural': 'Atores',
                'ordering': ['nome'],
            },
        ),
    ]
