# Generated by Django 5.2.4 on 2025-07-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(model_name='atores', old_name='nascionalidade', new_name='nacionalidade', ), ]
