# Generated by Django 5.2.4 on 2025-07-17 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='stars',
            new_name='estrelas',
        ),
    ]
